# fly.toml app configuration file generated for blackeconomy-bot on 2025-03-31T05:43:43Z

app = "blackeconomy-bot"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"
  cmd = ["sh", "-c", "node src/deploy-commands.js && node src/index.js"]

[env]
  PORT = "8080"
  # Don't put actual secrets here for security reasons
  # This is just for non-sensitive config

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[experimental]
  auto_rollback = true

[scale]
  count = 2
