# fly.toml app configuration file generated for blackeconomy-bot

app = "blackeconomy-bot"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  # Você pode adicionar outras variáveis não sensíveis aqui

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # ✅ Health Check HTTP
  [[services.checks]]
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[experimental]
  auto_rollback = true

[scale]
  count = 2
